### ISSUE TITLE
In-field Logistic/production command access

### ISSUE THREAD

**Issue by CurePindal** [Wyqer/kp_liberation#107]
It feels very restricting and 90s to only have access to logistics and production settings when close to a base. For modern in-field comanding it would be very helpful not to have to return to base for every tiny setup change.
Please make that options always available!
Thankies!

**Comment by Wyqer** [comment]
Production could be accessable also if near a sector. I'll take a look into it.
But Logistics is nothing which would be accessable outside of the FOB area due to the resource dependency.

Also you're free to edit your own used version as you like and change the conditions for the actions in the action_manager.sqf.

Production:
`if ((_fobdistance < _distfob) && (player == ([] call F_getCommander) || [] call F_isAdmin) && alive player && vehicle player == player && ((count KP_liberation_production) > 0))`

Logistic:
`if ((_fobdistance < _distfob) && (player == ([] call F_getCommander) || [] call F_isAdmin) && alive player && vehicle player == player && (((count GRLIB_all_fobs) + (count KP_liberation_production)) > 1))`
