### ISSUE TITLE
Unstored crates not saved

### ISSUE THREAD

**Issue by CurePindal** [Wyqer/kp_liberation#108]
We started a new game, build the FOB and the starting crates  had been dropped.
Then we had to restart the mission and the unstored crates have been gone.
Expected: Unstored crates are saved, too.
Can you add those crates to the save, please?
Thanks.

**Comment by Wyqer** [comment]
It's intended, that only stored crates will be saved.
Also not the crates are saved, the stored resource value is saved and on load the crates are generated due to the saved values for each storage area.
Adding each unstored crate to the save wouldn't only be a "adding classname" (what you maybe expected).
It would be needed to alter the savegame array with crates and also their current values, which will also need another loop in the savegame procedure. That's compared to the small amount of maybe unstored crates isn't worth a change (also inside a "stable" release their won't happen any changes to the save array due to patches). Also storage areas are free to build, so it's only a "take 5 minutes to store it" and nothing else.

Concerning the general question: I can, but I won't due to the stated reasons. And if I would, then also not in the 0.95X release.
