### ISSUE TITLE
Abort Logistics mission stuck

### ISSUE THREAD

**Issue by CurePindal** [Wyqer/kp_liberation#109]
- started a logistics mission only with a destination A (due to the GUI resize issue)
- waited until the timer ran out. nothing happened
- aborted the mission and now the logistic group is stuck in "Status: abort mission"

**Comment by CurePindal** [comment]
pic: https://steamuserimages-a.akamaihd.net/ugc/778406850968124365/37C42B21EF271C3ABD95EB719ED3C661F60F3782/

**Comment by Wyqer** [comment]
Create a mission with only one destination is catched since yesterday.
Referring:
https://github.com/Wyqer/kp_liberation/issues/105

In the Screenshot there is by the way no "resize issue".

So that creating a mission with only one destination is surely nothing which was intended in the state before yesterdays fix. Besides the fact that a logistic mission with only one destination is some kind of pointless.

So, again the question: at which commit state is your 951 you're using for testing today?
