### ISSUE TITLE
User Logistic Interface doesn't update status on bravo convoy

### ISSUE THREAD

**Issue by madpat3** [Wyqer/kp_liberation#110]
when assigning a truck to convoy bravo, the interface shows no status anymore neither of alpha nor of bravo. you have to close and reopen the interface.

and the status update don't work automaticly. you have to switch between convoys to update status. and if you have only one, you have to close and reopen the interface.

testet after implementation of changes you made here: https://github.com/Wyqer/kp_liberation/commit/d23fa8613bbdd674133699a8ba088e4e077611ea

**Comment by Wyqer** [comment]
> and the status update don't work automaticly. you have to switch between convoys to update status. and if you have only one, you have to close and reopen the interface.
It's intended, that the timer won't update during an open dialog.
That prevents the dialog to reload everytime when the calculations are done and for example resets the current entries in the mission planning fields if you haven't confirmed it.
Choosen because mostly you'll have only a look "how long at the moment" and not wait in the dialog for 5 minutes etc. to pass.

> when assigning a truck to convoy bravo, the interface shows no status anymore neither of alpha nor of bravo. you have to close and reopen the interface.
So everything is empty or what do you mean exactly?

**Comment by madpat3** [comment]
So everything is empty or what do you mean exactly?

yes. and greyed out buttons.

**Comment by Wyqer** [comment]
The greyed out buttons after buying a truck is something I've experienced also during my tests and is something I still want to optimize. Normally it waits for the server to finish updating the logistics data, sync the changes and if the client received the "not equal than before" data, the dialog will continue and refresh the values.

`if (buyLogiTruck == 1) then {
	buyLogiTruck = 0;
	[_listselect, _nearfob, clientOwner] remoteExec ["add_logiTruck_remote_call",2];
	waitUntil {sleep 0.5; ((_selectedGroup select 1) != ((KP_liberation_logistics select _listselect) select 1)) || (logiError == 1)};
};`

select 1 refers to the truckcount in the logistic data. _selectedGroup contains the data from the group before clicking the buy button (KP_liberation_logistics select _listselect) and KP_liberation_logistics gets synced between server and clients.

But you say, that everything (!) is without any (!) values or informations on your side? No entries in the left menu, no text anywhere, etc.?

**Comment by madpat3** [comment]
no no. like it is in the picture. but both convoys have one truck assigned and convoy alpha was enroute, before. 
after closing and reopening the interface everything is correct, again.

**Comment by Wyqer** [comment]
Ok, then it's the same what I encounter sometimes.
I'll have again a look for a bettwer working wait condition to ensure that after clicking he will wait until the new data is there and then finish loading the dialog with the new data as it's intended. But well.... the waitUntil condition don't work like it should and I can't really say why, because it looks all right. Maybe I'll try a slightly different comparison and look if that work as it should.

**Comment by Wyqer** [comment]
Please test it again with this change.

It would be great if you can report:
Does it reload after buying a truck?
Does it reload after selling a truck?
Does it reload after confirm a mission?
Does it reload after abort a mission?

**Comment by madpat3** [comment]
all matters confirmed with a YES :D
