### ISSUE TITLE
building menu 

### ISSUE THREAD

**Issue by madpat3** [Wyqer/kp_liberation#114]
when you're in the build-menu in the list of "buildings", the list is updating every 3 seconds. meaning you scroll down the list and after about 3 seconds the slider sets you back to top.

**Comment by Wyqer** [comment]
This has to be caused by receiving updates ressources data from the server. If the client receives new data, it will reload the build menu.
You are still using the 0.95 stable build, right?
Did you changed the resource multiplier maybe?
For 0.951 I've split the sync for ressources and for logistic/production. But basicly the new sync comes when:
* Resources at any FOB are changed (due to unstoring/storing/recycle/built)
* Slot counts or heli/plane counts change
* Combat Readiness changes
* Intel amount changes

referring: `\scripts\server\game\synchronise_vars.sqf`

And the build menu is updating with the condition:
`if (_oldbuildtype != buildtype || synchro_done)`
So everytime a sync is done or you selected a different entry in the list.

Hope it's fine with the split I've done in 951. If not, I will investigate further.

**Comment by madpat3** [comment]
i diddn't change the resource mutiplier. value is 3 meaning 1X.
and im using stable, with the changes you did in "open_logistic.sqf"

**Comment by Wyqer** [comment]
Ok.... I'll release the patch (951) tomorrow. That should influence the scroll bar bug, so let's wait for it and if you encounter it also in the 951 then, please provide me a server.rpt with debug on (savegamedebug can be false)

**Comment by Wyqer** [comment]
and this will get to #102 then. Closed here.
