### ISSUE TITLE
Suggestion: Civil spies/informers

### ISSUE THREAD

**Issue by lolloscout** [Wyqer/kp_liberation#123]
It would be nice to have the ability to interact with the local population for information (intel points)

**Comment by Wyqer** [comment]
For 0.96 is planned to release a civil reputation system with benefits/penalties depending on the reputation of your side.

**Comment by lolloscout** [comment]
I write here because I do not want to clutter the page of "proposals": if I'm not present it would be cool to have OPFOR air patrols (I find it strange that I am invading an enemy-controlled territory but I can safely fly over their airspace by helicopters and airplanes.
Also sometimes it happens that the player can enter an enemy sector before the enemies spawn, so can you expand the range of activating sectors from 1km to 1.5km?

Thanks for your attention and sorry, I'm annoying

**Comment by Wyqer** [comment]
Nothing to say sorry for, all reports and suggestions help.

Concerning the air patrols...
I really know what you mean and yeah it's some kind of "why can we just enter their airspace without being killed". But as it's ArmA a enemy fastmover in the air would give you real trouble. Also with the new sensors update one enemy jet could annoy you the whole time with shooting your vehicles, etc. You wouldn't be save inside a vehicle if a jet is around most the time.
They appear after a certain enemy awareness is reached at the moment, but not directly at the start (even if it would be more immersive).

About the spawning....
Spawning of the enemy is always depending on the serverload etc.
If you engage a town as infantry you shouldn't experience any sector where you can walk to the center and no enemy is there (full blue bar). Only if the server can't handle the mission or hadn't a restart for 6 hours or something. If you use a HMMWV or Helicopter and directly drive/fly to the center, then sure.... it can happen that no enemy is around because you've traveled the 1km spawn distance so fast.

I'll have a look at our international session (so many players around) to this behviour and maybe also experience a reason for adjustment. If you want to participate by the way:
https://www.killahpotatoes.de/calendar/index.php?event/338-international-kp-liberation-session/

**Comment by lolloscout** [comment]
thank you again Wyqer. 
I wonder if it is possible to limit the use of jet sensors or (if limit sensors are impossible) adding just heli patrols composed of transport helicopters that have only miniguns or similar

**Comment by Wyqer** [comment]
Hrm.... heli patrols could maybe be suitable.
I'll have a look at it during development of 0.96.
Thanks again.

**Comment by lolloscout** [comment]
You're welcome! I really hope you'll add this feature

**Comment by Wyqer** [comment]
Informant implemented.
Enemy "air control patrols" or mechanics will be looked at after 0.96
