### ISSUE TITLE
AI does not dismount vehicles once got in or not in players squad

### ISSUE THREAD

**Issue by nirtulys** [Wyqer/kp_liberation#132]
### Basic Information
**Mission version:**
0.952

**Map used:**
Altis

**Mods used:**
Ace on server
Ace, CBA, C2 Command and Control, sthuid on client

**Dedicated or local game?**
Dedicated

**GitHub or Workshop mission file?**
Workshop

### Individual Things
**Did you edit anything within the mission files?**
No

### Short Issue Description
Friendly AI squads/units does not dismount vehicle

### Expected Behaviour
AI should be able to get in/get out from vehicles

### Steps to Reproduce the Issue
Buy vehicle (f.e. truck), buy AI squad or unit (crew option). Command them to get in vehicle via Zeus. Command AI to dismount. And nothing happens, except Zeus notification about not being able to edit.

**Comment by Wyqer** [comment]
To get AI out of vehicles you've three options (which all work in Liberation, tested it because of your report two minutes ago)
Driver in Truck (1st Group) and AI Fireteam (2nd Group)

1. Give the driver a unload transport waypoint -> truck will arrive at waypoint -> Fireteam will dismount
2. Give the driver a get out waypoint -> truck will arrive at waypoint -> driver will dismount
3. Select one of the groups and press G -> Selected AI will dismount

**Comment by nirtulys** [comment]
I feel pretty stupid right now. Thank you for this information.
