### ISSUE TITLE
Suggestion: parameter for free production/logistic actions

### ISSUE THREAD

**Issue by CurePindal** [Wyqer/kp_liberation#141]
Hello Wyqer!
Could you consider to add a mission parameter to unlock the production/logistics actions for all players?
We usually play in a small group where every engi/medic is needed so we barely have the capacity for a dedicated commander. And its a bit annoying that you have to switch slots just to handle production for a few mins.
Thanks!

**Comment by Wyqer** [comment]
It will prevent any mismatching or issues due do simultaniously changing production or logistic settings. So, no implementation from my side. But feel free to remove the condition to be the commander from the action_manager.sqf on your own risk.

**Comment by CurePindal** [comment]
> It will prevent any mismatching or issues due do simultaniously changing production or logistic settings. So, no implementation from my side.
Wouldnt that be really easy to prevent by blocking the menu when its already open?

**Comment by Wyqer** [comment]
It's not a problem from coding to implement a small blocking flag variable and sync it on change through the network. But also that's the point of vulnerability concerning connection and lags.
Beside of that the commander role is for reason the most important one. Additional it's a kind of "implementing something because I don't want to spend 10 seconds of my time", which is not meant in a negative, but in a very general way.
If you want to change it in your group do the following change or ask your admin about it and you've what you want. But I won't implement it in the official framework.

`scripts\client\actions\action_manager.sqf`
Line 236
Change:
`if (((_fobdistance < _distfob) || ((count _prod_sector) == 12)) && (player == ([] call F_getCommander) || [] call F_isAdmin) && alive player && vehicle player == player && ((count KP_liberation_production) > 0)) then {`
to:
`if (((_fobdistance < _distfob) || ((count _prod_sector) == 12)) && alive player && vehicle player == player && ((count KP_liberation_production) > 0)) then {`

**Comment by Applejakerie** [comment]
Coming from a small community myself I see what you're getting at CurePindal but as Wyqer stated it is very much a case of "can you do this so I can save 10 seconds". May I suggest hopping roles or if you're not using ACE - to set your revive parameters so that all roles can revive using a FAK? Medics would still be able to use a medikit also. Again, putting in the block method you're asking for would depend on the fact that no two players would ever access the UI within the same second/two seconds. There cannot be a check every 0.1/1 seconds, that's bad for performance I'm sure, etc.

**Comment by Applejakerie** [comment]
If you happened to get two players on the UI, I don't think the consequence would be worth the solved issue you're trying to raise. I set my revive so that all can revive at 8 seconds, medics can revive with medikits in 4 seconds. It makes more sense given every soldier has some decent training in first aid and FAK come with a harsher penalty than medikit given they are used up per revive. In this setting, I play as Commander and lead my team to victory. ;) Hope this helped clear things.

**Comment by CurePindal** [comment]
No clue what youre talking about, Applejakarie, but when you have a group of AIs you cant just hop into the command slot to manage production and swap back.

**Comment by Applejakerie** [comment]
Make the change Wyqer suggested, work with your friends to make sure no two people are using the UI at the same time. Don't expect support on any issues in consequence considering it's not an official feature. Because of the way the game engine would check to see if the panel is already opened, the block method you mentioned is unsuitable. Happy playing. 😃
