### ISSUE TITLE
.953 Vehicles not saved

### ISSUE THREAD

**Issue by CurePindal** [Wyqer/kp_liberation#143]
### Basic Information
**Mission version: .953
**Map used: altis
**Mods used: vanilla
**Dedicated or local game? local host
**GitHub or Workshop mission file? Git

### Individual Things
**Did you edit anything within the mission files?**
no

### Short Issue Description
Most vehicles are gone after reloading the mission
- Tanks gone
- MHQs gone
- Huron reset to the carrier
- ammo truck gone
- repair container gone
but: tank truck and our Huron FOB container are still there

### Expected Behaviour
Vehicles are saved and loaded properly

### Steps to Reproduce the Issue
Local host
close mission
startup mission again
stuff gone

### Screenshots, Serverlog or any other helpful Information
unfortunatly not. will add info from a rpt when i try to replicate the issue on my host.

**Comment by Wyqer** [comment]
Well, this is really something I can't reproduce on my side and can't be a common bug. If it is, than everyone would have issues with saving and many many many people would report it.
So I would really appreciate a log with activated debug messages. Also activate the savegame debug in the kp_liberation_config.sqf.
Just play some minutes so that you've some stuff at a FOB, load the save again and hand over the rpt, if it occurs again.
Without log and both (!) debug options enabled I can't investigate what happened on your side.

**Comment by CurePindal** [comment]
Quick question: Seems all stuff that wasnt saved was outside a FOB.
Is Bluefor stuff outside a FOB supposed to be saved or not?

**Comment by Wyqer** [comment]
No, it was never supposed to be saved if outside the FOB range.

**Comment by CurePindal** [comment]
Ok, got some feedback from the host. Was indeed stuff thats outside the FOBs, so this is a dud.
Hm, maybe helpful to add info about the save routine and save file (location) to the wiki?

**Comment by Wyqer** [comment]
Already half way done concerning save mechanic, move saves from one machine to another, etc.
But basicly adding the stuff which is new to liberation was more important. But the wiki will contain it before it's finished, sure.

**Comment by CurePindal** [comment]
Fully agree.
Keep up the great work! Its amazing!
