### ISSUE TITLE
Suggestion: Buildings should never be safe

### ISSUE THREAD

**Issue by SondreBakken** [Wyqer/kp_liberation#145]
Liberation has always been a bit predictable. When moving towards an enemy sector, or when being dropped in behind enemy lines you knew nothings is going to go down before you see that red bar  on the right.

Talking to a friend that had been deployed twice made me come up with this suggestion that should not be to hard to implement.

Based on a distance to the player (say 1000 m radius) there should be a chance of insurgents spawning in houses. The chance of insurgents spawning should be based on the distance to nearest captured sector or fob to simulate stability in areas controlled by you. This way when moving around every house is a potential threat that has to be checked out and moving in armoured cars  even when deploying before an assault makes sense.

These insurgents should not make the map tile go red since this is based on radio activity and radiotowers. So it should not be possible to just keep an eye on the map and then never be surprised

**Comment by FatRefrigerator** [comment]
I agree it'd be nice to have a bit more unpredictability in regards to enemy movements and locations.

The problem is that you will encounter the same issue as with the sectors. They take time to spawn in and so would these random spawns outside of sectors. So you'd end up having them either spawn on top of you or spawn behind you,unless you slowly approach every building you see.

**Comment by SondreBakken** [comment]
But we are just talking about a few men. And if u just set up a good range
it shouldnt be a problem. What you talk about is a technical issue that i
am pretty sure can be solved by some good code

**Comment by Wyqer** [comment]
I'll have a look into that. Especially how to implement it in a reliable way concerning spawning etc.
