### ISSUE TITLE
Suggestion : Starting ressources 

### ISSUE THREAD

**Issue by Blackhawk-Michael** [Wyqer/kp_liberation#149]
How about placing the start ressources on the Freedom, that have to be lifted to the first F.O.B.  ?
Or taking another Huron Container, that is being able to be dismantled, so the ressources spawn there ?

That would bring more action into the logistic and we wouldn't have problems with the ressources stucking in tree's or something like that.

**Comment by Wyqer** [comment]
placing the start resources directly on the freedom would increase the time for players until they've them available at their first FOB. Also some players don't have the heli dlc and will only play with a vanilla preset. They'll use a preplaced FOB and then they've to transport it from the Freedom through maybe enemy territory 6 times (as they can't fly the huron) with a little bird. That's why they're provided via paradrop.

Basicly I like the idea about a "big container" which can be "unpacked" to the 6 start resource crates. I'll think about it some more the next days, but yeah.... that could be a good compromise concerning providing of the starting resources.

Maybe also other people have ideas or thoughts concerning this suggestion.

**Comment by Applejakerie** [comment]
I very much like the idea of unpacking a large cargo box or something, just not sure about the weight (sling loading capability regarding container models). Maybe there could be two new parameters to help those without Heli DLC - start with Mohawk, not Huron (problem is it only pertains to vanilla preset) - or start with additional ghost hawk (like before however the problem is (and thus was removed since) it is armed, naughty for start game). :/

**Comment by amunoz20** [comment]
Time ago I stated this problem with helis DLC for non DLC players. The idea was to have a switch statement which check if the commander or the one who is acting as host has helis DLC the initial Spartan would be huron, if not it would be a Mohawk or something else... And you can add as many cases as you want. 

It is correct that ghosthawks are armed but so is the spartan when RHS is enabled. I personally dont think that unit gives to much of an upper hand for players, but thats just me :P
