### ISSUE TITLE
GREUH-Script

### ISSUE THREAD

**Issue by madpat3** [Wyqer/kp_liberation#15]
the greuh option "in vehicle sound volume" isn't working, when using ace3.

it seems the script is overwritten, by ace.

**Comment by kaso2mod** [comment]
@madpat3 if you want reduce the noise on a vehicle use caps , add them to your equip from the virtual arsenal.

**Comment by madpat3** [comment]
![photo-773712](https://cloud.githubusercontent.com/assets/15272840/24841441/ec60850c-1d84-11e7-91b1-46ce7c022484.jpg)

**Comment by kaso2mod** [comment]
haha just joking bro :)

**Comment by Wyqer** [comment]
It's right, that it won't really work with ACE enabled.
In ACE you've in fact the earplugs and no "magic less noisy engine sounds", as ACE is a realism mod.
But well, that's no new information for you, I know ^^
So at the moment there are no plans to build a workaround around ACE for this. Because the reason it is not working is, that ACE is take over the volume controls, not that Liberation detects ACE and disables the control.

Maybe you can delete the ace_hearing.pbo (just a thought)

**Comment by madpat3** [comment]
nah, nevermind.
i'll reduce the ingame sound while sitting in a helicopter and talk.
