### ISSUE TITLE
Suggestion: Radio towers - reinforcements - POIs

### ISSUE THREAD

**Issue by CurePindal** [Wyqer/kp_liberation#158]
### Short Issue Description
We played the new Lib a lot in rather small groups (2-7 players usually).
We noticed that the impact of disabled radio towers for our attacks has a pretty high impact. A disabled radio tower usually means that its somewhat a cakewalk to take a location, while its way more of a struggle if an active radio towers brings in reinforcement. 
Thats definatly nice, but the gap between "easy" without a tower and "challenging" with an active tower seems to be too broad.

### Suggestion
1. Some important locations (like airfields, the main towns, bases/bases with vehicle unlocks etc) should always be considered to have active radio towers to keep the battle a challenge. 
(We're not sure, but it seems that main towns get constant reinforcements already? I ask, because we also had some suprising easy main town battles with 2-3 players)

2. Even with a disabled tower there could be a random chance that reinforcements show up. Would spice up things.

Thanks for considering. Keep up the great work! =)

**Comment by Wyqer** [comment]
The important targets are always covered by more than one radio tower in the maps I've provided.
And with 2-3 players you'll have a "easy" experience due to the "adapt to playercount" functionality, which is enabled by default. Can't say if you've deactivated it in your game with that small group.

Concerning the general thing you mention, I can only say that 96 will aim to everything "enemy related" stuff, which isn't touched until now and is still on the state of 924.

After my upcoming exams I'll start on 96 and I'll provide discussions in the discord concerning my thoughts and provide also the experimental versions as before.

I guess I can create a 96 which will suit the community, as the community will be involved.
