### ISSUE TITLE
Support DUWS like support calls

### ISSUE THREAD

**Issue by steelbrain** [Wyqer/kp_liberation#16]
Sometimes, it's really nice to be able to use the UAV support call in DUWS, It shows the one or two enemies hidden in really weird places and saves tons of times when playing alone in local mp.

Is it possible to add some of those support calls to Liberation?

**Comment by Wyqer** [comment]
At the moment, there are no plans to extend the SP functionality.

Liberation is a MP Mission, which you can play as a kind of SP via local LAN game. But the focus is on the MP part and because of that I'm working at features / reworks, tweaks and updates and not on any SP part. Maybe in a much later state I'll think about some SP things.

**Comment by ChiefOwens** [comment]
One way around your issue is to place a small uav down and carry and uav handheld device ( cant remember name ) in your equipment slot. You can then launch that device anytime. I usually send the small UAV into an area before the troops get there. It pops the enemy ai and I can see what I need to do or find those ai that like to hide.
