### ISSUE TITLE
Headless clients and kill counts

### ISSUE THREAD

**Issue by Exploitexe** [Wyqer/kp_liberation#161]
### Basic Information
**Mission version:** v0.954
**Map used:**  Tanoa
**Mods used:** 17:
          Enhanced Movement
          CBA_A3
          BWMod
          ace
          Suppress
          KP Ranks
          JSRS SoundMod
          JSRS Soundmod - Additional Weapon Handling and Reloading Sounds
          Immerse
          FA-18 Super Hornet
          ATLAS Mod: LHD PLUS
          Advanced Urban Rappelling
          Advanced Towing
          Advanced Sling Loading
          Advanced Rappelling
          ACEX
          ACE3 - BWMOD Compatibility

**Dedicated or local game?**  Dedicated with 3 Headless clients
**GitHub or Workshop mission file?**   GitHub

### Individual Things
**Did you edit anything within the mission files?**
          I have not made any changes to the mission files

**If yes, what did you edit exactly?**

### Short Issue Description
         (Main Issue:)
         We play every night the kill counts do not seem to be accurate.

         (Side note:)
         Also We would love an option to place greater load onto the headless clients in the server options 
         screen as it seems most of the vehicles (400+) get controlled via the server along with a bunch of 
         AI, if we could push some more AI onto the Headless clients via the server options menu that 
         would be sweet.   

### Expected Behaviour
        Accurate Kill counts

### Steps to Reproduce the Issue
        Playing

### Screenshots, Serverlog or any other helpful Information
         Let me know what you would like for information for this issue.

Thanks,
love the mission!

**Comment by Wyqer** [comment]
A serverlog would be good concerning your thoughts.

For the behaviour and scripted handling of HCs in Liberation:
The server will run all calculation scripts for production, logistic, saving, FOB data, sector data, etc.
If a HC is connected the HC get's all AI units transfered on the spawn of the units. (except blufor units, which will always be local to the machine of the player who selected the Platoon Leader role)

Example:
https://github.com/Wyqer/kp_liberation/blob/master/Missionframework/scripts/server/patrols/manage_one_patrol.sqf
At line 53

The count which is labeled as "vehicles" (should maybe rename it to prevent confusion like this) isn't the count of "enemy vehicles" or similar. It's the count of [vehicles](https://community.bistudio.com/wiki/vehicles), which is basicly everything which isn't a map object. For example all parts of preplaced military bases on maps (walls, decoration, buildings, etc.).
Real AI is the [units](https://community.bistudio.com/wiki/allUnits) counter at the FPS information markers in the bottom left of the map. If you directly start playing with HCs connected, this counter should be much higher at the HCs as on the server (mostly the server state 0 Units).
The server.rpt should show you diagnostics beginning with `[KP LIBERATION] [STATS] Source: Server`
The HC logs will give you also informations like that in their logs.

With how many players do you play by the way? 3 HCs is very much and mostly not needed. Also concerning HCs "more is better" won't be true. For example we're playing on our international sessions (30-40 players, so we also expanded the playable units count) with one HC and don't have any issues concerning drops or strange behaviour. The event take 5 hours. So if you're not playing with more (which isn't possible as you didn't made edits) you would never need 3 HCs running. Wouldn't improve anything, mostly it'll be worse than running without HC or maybe one HC.

Concerning the kill countings. Do you mean the "player score"? That can be caused (also if you mean the statistics which will be shown after you finished a campaign) by the different locality of units in an MP environment. This isn't anything I've touched since I take over the development but will be optimized during the work on 0.96.

I'm wondering by the way, why you're playing with the ATLAS mod?
And as a heads up -> You can update to 0.955 without loosing any progress, as the savegame is compatible between each 0.95x version. And as you didn't edited anything you could just replace the pbo with the actual one.

**Comment by Exploitexe** [comment]
you rock sir! so right now its maybe 10 people a night playing at one time, Hope for more in the future :) The dedicated is on a 2012 server with dual quad xeons (x8) at 3.12GHZ along with 1 HC all on 15k drives. I then have a 2nd 2012 server with dual quad xeons (x8) at 3GHZ with the other two HC on 7200 rpm drives running through an IPSEC tunnel to the main host both sites of which have full 1GIG up and down for bandwidth. the HCs are at 4 for a ping so I didn't think this to be a lag issue.
Thanks for explaining the vehicles count, that makes more sense now.
I find if I set the "Maximum amount of AI units" to 150 - 200% the unit cap does not get hit so often and the server then can spawn in more AI as we fly over towns and such. (could be wrong about this)

it is indeed the "player score" that people are having the issue with, they want to see how good they are doing :)

I thought ATLAS was required, but I just went back and see:
"Replaced: ATLAS LHD with USS Freedom. Thanks to Applejakerie for the immersive clutter on the carrier"
so maybe its not needed?

Thanks again for your work on this

**Comment by Applejakerie** [comment]
No you don't need the Atlas LHD at all anymore. The USS Freedom is free content from BIS so it's better to use that (although we all might agree the USS is worse if it is the final version) instead of require a mod dependency or waste land for a "Chimera" base. :)) I also +1 for a working player score, I've noticed it "misses" a lot of kills too but can happily wait for 0.96 for improvements there.

If you want to use Atlas or Nimitz for example, it's a pretty simple change but that mod will become dependent for the mission to run properly, that's dependent for every client joining too. Happy playing. :))

**Comment by Wyqer** [comment]
So for 10 people and 150-200% enemy count I would recommend using one HC on the same machine. (so you shouldn't need the two HCs from the other root) Bandwitdh isn't a problem than, yeah. I would guess that's quite enough to handle a 10 player game with a highter enemy count very good. As long as the FPS of the server and HCs stay in average at about 30, it's totally fine. Even >20 is fine.

But back to the player score topic:
You're running ACE and I guess with medical and cookoff features enabled.
If you don't set the medical functionality will only apply to players and also AI could be unconcious and is affected by the ACE medical system, then you can have problems with the player score concerning Infantry kills. As then sometimes you're not the one who really killed the soldier as it was a script which finally end it.
The cookoff feature from ACE (which is really good in my opinion) is basicly the same as for the infantry with affected ace medical. You shoot an APC, then the fire comes out and shortly after that it explodes. Same here, that the "finishing kill" is made by a script and not by a player.

Here is also a old issue on the ACE GitHub, which is about that:
https://github.com/acemod/ACE3/issues/3111

And maybe you want to try this one than:
https://github.com/acemod/ACEX/tree/master/addons/killtracker
