### ISSUE TITLE
suggestion disable automanufacturing

### ISSUE THREAD

**Issue by madpat3** [Wyqer/kp_liberation#176]
when capturing a factory sector and building a storage area, the sector automaticly starts producing supplies. supplies you maybe don't need, and if you forget about it or the commander isn't on the server your storage rooms are full with unneeded supplies. in my opinion it should only start production, if the commander orders it to.

**Comment by Wyqer** [comment]
The default production was implemented due to #99 
I think a default production with a "oh, we have now a full storage there" is nicer for most players as a "We forgot to activate the production, we've lost a lot of time now".
The resources can just be unstored and will be deleted on restart, as long as they are not inside a storage area.

**Comment by madpat3** [comment]
or maybe revolving the recource type. capturing one factory, automaticly starts producing supplies, the next one automaticly produces ammo and the next one produces fuel and repeat
