### ISSUE TITLE
suggestion osprey

### ISSUE THREAD

**Issue by madpat3** [Wyqer/kp_liberation#178]
since the vanilla osprey (vehicle-transport) is able to load ressource-boxes, you should disable that function, when the plane has loaded a vehicle already, and vice versa.

**Comment by Wyqer** [comment]
I'll look into a blocking for that.
Basically the trucks can also be fully loaded and infantry can sit in the back "inside" the crates atm.
But for the Blackfish I can have a look.

**Comment by Applejakerie** [comment]
I'd say it's worth blocking infantry from sitting in back "inside" the crates too. Like in certain game modes, you jump into a certain seat and it just jumps you straight back out again. The tough part I guess would be making it so it only blocks seats taken up by crates, so that if 1 crate was loaded, those seats in the spaces of the other 2 crates would still be available.

**Comment by madpat3** [comment]
well, i'd say for the infantry version, you can leave it as it is. 
in reality, they have for example parachute troops jumping out of the sides of the plane, while their support stuff, vehicles etc. is being parachuted out of the back of the plane. so you can have troops and those boxes loaded, while in the vehicle version there is visible not enough space for boxes and vehicles.

**Comment by Applejakerie** [comment]
Oh I didn't clarify, my bad. I was talking about the infantry trucks. ^^' 

I totally agree with you there.
