### ISSUE TITLE
Suggestions "JETS"(LOADOUT SCRIPT), Translation ... 

### ISSUE THREAD

**Issue by doodzio** [Wyqer/kp_liberation#216]
I have small questions & suggestions.

Why  don't you  add jets from dlc by default? 
And in question of jets DLC [ script to edit jet weapon loadout ](https://forums.bistudio.com/forums/topic/204747-release-gom-aircraft-loadout-v134/)
What you think about placing jets on deck of USS FREEDOM i did it in my mission but they wheels sink into deck so i had to add unflip action.

About boats. I was thinking of teleportation script from bridge to hatches under elevators with camera preview like this one you see when choosing fob to deploy on.
There is +4 of those "mini decks" don't know how to name it.

Some time ago i was thinking about ( [inidbi2 ](https://github.com/code34/inidbi2)/ [inidbi for linux ](https://github.com/newtondev/inidb-linux)) on server side for whitelist but I am still not to good in remote exec and sync with clients.
I ended with moderator slot ( with zeus ) using F_isSuperAdmin  ( serverCommandAvailable "#exec ban") and default commander slot using F_isAdmin.

I can help u with stringtable for Polish translation. I wrote one but i have to fix it in some places.
[My uncomplete unfinished messed-up repo ](https://github.com/doodzio/greuh_liberation_doodzio.Altis/tree/SGcustomizedStatic8.17)

**Comment by Applejakerie** [comment]
I won't answer all of this, some parts I can't. 

The DLC Jets is added by default, make sure you're up to date. The loadout script might be a good idea but it could also be a "if you need, feel free", others might have other implementations and we don't like to depend on third party code for anything. I don't think adding Jets to the USS deck is at all likely, for one these are vehicles to be purchased, not handed out for free and for two, they're extremely over-powered for the start of the game, however, an unflip action on the deck could still be a great idea, for those landing on the deck later on.

**Comment by doodzio** [comment]
I checked now vehicles list sorry for that about "JETS" I have to update my files.

Thanks for your quick reply.

**Comment by Wyqer** [comment]
Hey there, thanks for your feedback. Let's get to each topic of yours.

**Jets:**
As Apple already mentioned, they are part of the default presets since the jets DLC is released. :)

**Loadout Script:**
Same concerning Apples words. I won't implement any third party scripts for some reasons:
* Mostly they come with much more functionalities as needed (harsh example: use RHS for one rifle)
* It's not my code, so I've to read into it and this isn't always a nice work. Depending on the coder who wrote it.
* I've surely to adjust some things in the code for Liberation, which could be a problem concerning a different license compared to Liberation
* Maybe the script get broken after an update or something. So it could be that there will be an dependency to the update schedule of the coder of the script
* And also: I like to solve problems with my own solutions instead of "just put a script from someone somewhere"

**Boats:**
I'm also disappointed about the Freedom in comparison to the Nimitz concerning "under deck environment". On the Nimitz you where able to get to the aft of the ship. Currently there is only jumping into water on the aft of the Freedom or, if you use the advanced urban rappeling mod, rappel down into the water. I already thought about something "nicer", but I've come to the conclusion that it's not worth the effort. The Freedom isn't intended to be a "most times used operation base", as you can't do anything there concerning building, resource storage, etc. It's just a "nice immersive place to start from", nothing more (same like the ATLAS LHD from the old Liberation missions). And therefore the boats etc. are mostly only used once at the campaign start. So I think there are much more things which need to be done and have a higher priority as coding some small things for the carrier environment.

**Translation:**
I would really appreciate any contributions with translations. So if you're ready and like to share it, I would be glad if you create a pull request to the 0.96 branch.
