### ISSUE TITLE
Suggestion: Resistance Tiers

### ISSUE THREAD

**Issue by matr1x001** [Wyqer/kp_liberation#247]
The current presets for resistance provide a great level of customization (units, vehicles, transports, weapons, uniforms, vests, headgear and facegear), however it could be achieved and allow for easier customization using simply unit and vehicle types of each faction already within gref. The factions contained within gref have a fairly good level of diversity of equipment, weapons and vehicles that could be used to create much simpler tiers without the need to completely customize each tier of units, as is done currently.

For instance gref conatains:

- ChDKZ Insurgents
- Chernarus (Air Force)
- Chernarus (Ground Forces)
- Chernarus (National Guard)
- Chernarus (U.N. Peacekeepers)
- Nationalist Troops

The factions listed represent differing levels of equipment and vehicles, therefore strength in combat and capability.

Please consider adding presets using the tiers of gref factions (class names) - if only units and vehicles, as well as a preset to customize every single item a unit has and will use.

Example of gref faction tiers that could be used

- Tier 1 - Nationalist Troops\Miltia

Units: 
rhsgref_nat_commander
rhsgref_nat_hunter
rhsgref_nat_militiaman_kar98k
rhsgref_nat_rifleman
rhsgref_nat_rifleman_m92
rhsgref_nat_saboteur
rhsgref_nat_scout
rhsgref_nat_warlord

Vehicles:
rhsgref_nat_uaz
rhsgref_nat_uaz_open

Transport Vehicles:
rhsgref_nat_ural
rhsgref_nat_ural_open

- Tier 2 - ChDKZ Insurgents

Units:
rhsgref_ins_g_commander
rhsgref_ins_g_machinegunner
rhsgref_ins_g_medic
rhsgref_ins_g_militiaman_mosin
rhsgref_ins_g_rifleman
rhsgref_ins_g_saboteur
rhsgref_ins_g_sniper
rhsgref_ins_g_squadleader

Vehicles:
rhsgref_ins_g_uaz_ags
rhsgref_ins_g_uaz_dshkm_chdkz
rhsgref_ins_g_uaz_spg9

Transport Vehicles:
rhsgref_ins_g_gaz66
rhsgref_ins_g_gaz66o

- Tier 3 - Chernarus (Ground Forces)\Infantry (Para)

Units:
rhsgref_cdf_para_specialist_aa
rhsgref_cdf_para_grenadier_rpg
rhsgref_cdf_para_engineer
rhsgref_cdf_para_machinegunner
rhsgref_cdf_para_marksman
rhsgref_cdf_para_medic
rhsgref_cdf_para_squadleader
rhsgref_cdf_para_rifleman

Vehicles:
rhsgref_BRDM2
rhsgref_BRDM2_ATGM
rhsgref_BRDM2UM
rhsgref_BRDM2_HQ

Transport Vehicles:
rhsgref_cdf_gaz66
rhsgref_cdf_gaz66o

**Comment by Wyqer** [comment]
Hey there.
Thanks for the huge suggestion. I'm sorry to say that this won't be done.
Reasons are that the "complex" but therefore very individual customization of resistance units is intended. With "only classnames" there wouldn't be the possibility of providing that much diversity as it's possible now.
And the most important reason: Liberation won't get any mod dependencies in the basic code (except the terrain, of course). Using your suggestion would make RHS GREF an always needed mod to play Liberation.
My goal is to keep Liberation totally mod free, with a good variety of "already supported" mods.
Due to the MIT License you are free to fork the repository, edit the resistance tiers and spawn mechanics like you suggested and use this in your community or even publish it somewhere.
But in the "official" version there won't be any change which leads to a "hardcoded" mod dependency.

**Comment by matr1x001** [comment]
what I am suggesting is actually another preset much like what is already in use for civilian factions, that suggestion is only in relation to the rhs gref preset for resistance not anything else. I certainly did not make any comment about removing anything or making it mod dependent. All of the custom presets for arsenal, civilian, blufor and opfor units use mod class names which makes them mod dependent if selected, another preset could be done this way. Your explanation doesn't help me understand why a resistance (gref) preset has been added, which requires loading the mod, if only to use such a small portion of it's content. What type of resistance faction are you trying create if nothing other than unique? I actually believe the addition of gref as with the other rhs presets to this mission has been a good idea and I can't see the several factions in gref being limiting to diversity. Adding a gref preset and scripting the layout of vanilla units using gref gear just seems a little odd is all.

**Comment by Wyqer** [comment]
> I certainly did not make any comment about removing anything or making it mod dependent.

> it could be achieved and allow for easier customization using simply unit and vehicle types

> that could be used to create much simpler tiers without the need to completely customize each tier of units

Because of the last two quotes I assumed you want to replace the current resistance tier system with a "only state units and vehicles, not equipment" which then uses GREF classes by default.

As you now explained you're talking about a preset:
Feel free to extend the current GREF preset from @FatRefrigerator or give him some input so he can update it.
A change from the "tier equipment" to a "tier units" won't happen, because vanilla FIA etc. don't provide the diversity I want for the resistance, so the current equipment tiers are the best way to achive it even with assets from vanilla game or mods which don't provide a huge variety of "preequipped" units.
