### ISSUE TITLE
Feature | Blacklist areas

### ISSUE THREAD

**Issue by Tress16** [Wyqer/kp_liberation#253]
Would be a nice feature if areas could be blacklisted in the **kp_liberation_config.sqf** (area marker with variablename in mission.sqf maybe called OPF_1, OPF_2, ...) for Liberation actions like (civ placement, mil placement, secondary tasks, asymetric warfare, ...) so the mission makers can define zones for bases, special places or own tasks.

**Comment by Wyqer** [comment]
Markers already have unique variable names in the mission namespace.
And what do you mean exactly with "the mission makers can define zones for bases, special places or own tasks."
I don't know what you're up to.

**Comment by Tress16** [comment]
E.g. I wanna build a base without spawning civ's, mil's or tasks in this area.

**Comment by Wyqer** [comment]
Ok, I also had a short talk with people on the discord (to which I would really like to invite you, it's only text chat), because I'm still not sure if I understand what you really want.
So my understanding is now e.g.:
You have the an airfield on a map. There is a military sector defined. You want this airfield for an own base, or maybe own (with full zeus) created tasks. So you would like to have an array in the config in which you can enter the marker names ("capture_12","military_15", etc.) and at this markers shouldn't spawn any scripted content.
If I'm right with this, I would recommend to just open the editor and delete the marker, as you also have to open the editor to look for the marker name to enter this in the suggested "blacklist" array.

If I'm still wrong, I would appreciate a talk about this on the discord. Even in german, if you like ;)

**Comment by Tress16** [comment]
OK, maybe I don't undestand how this mission framework work.

**Question:**
If I delete all the markers in the Altis Airbase area can spawn their any objects like enemy forces, civillians, secondary tasks, asymetrics, routes from a to b given the units or other stuff that could collide with my placed objects by the 3den editor? Or will it destroy the system (creating enemy attacks, save game, ...) in any way?

**Comment by Wyqer** [comment]
If there are no markers, there won't spawn anything.
So you can edit the mission.sqm (via editor) and delete areas etc. before you start a campaign. I wouldn't recommend to delete sectors without starting a new campaign.

**Comment by Tress16** [comment]
OK. Thx a lot. Slowly, it begins to become logical.^^
I'll try it on the next start of a new campaign.

I'm using ALiVE for more actions around the official zones.
Using the CQB-module for spawning syndicate in buildings.
