### ISSUE TITLE
Suggestion | Change folder name

### ISSUE THREAD

**Issue by Tress16** [Wyqer/kp_liberation#264]
It would be nice if parts of the folder structure would be redesigned. So **"res"** renamed in **"images"** and the parts of the images for the ui could be putted in a new folder called **"images\ui\"**. All for a better usabilty.

**Comment by Wyqer** [comment]
In the current codebase there won't be a change in the structure.
Reason is, that I'm already working on a rewrite of the whole code of the mission beside of the normal work on Liberation.

It's currently not on a repo on GitHub, but here is the part from the readme, which fit to your suggestion:

### Goal
* Modular and therefore much cleaner structure
* More streamlined code
* Performance improvements due to code optimizations
* Easier ways to debug
* Easier ways to add additional gameplay aspects due to the modular framework
* There should be no need to do any additions in any `mission.sqm` (removing would be ok)
* Personally: Using this project to get more familiar with SQF and the Liberation mission itself than before

### Conventions
* Global variable naming: `KPLIB_moduleName_variableName`
    * moduleName: The name of the module like `init` or if it is kind of a global category like `preset` or `param`
    * variableName: Name of the specific variable like `heavySquad` or `adaptiveEnemy`
    * Only some very rare variables have no moduleName, as they are not directly connected to a module. Example `KPLIB_milAlphabet`
* Function naming: `KPLIB_fnc_moduleName_functionName` (same rules like for the variables)
* CfgFunctions Framework
    * `KPLIB_functions.hpp` in missionroot as central fetching file
    * Each module has an own `functions.hpp` which is included by the `KPLIB_functions.hpp`
* Modular structure
    * Naming for modules: `loadOrderNumber_moduleName` like `0_init` or `1_core`
    * Each module will handle one aspect of the game. For example the initialization, core mechanics, enemy spawn, civil reputation, etc.
    * General structure:
        * `fnc` folder for functions and one-time-procedures
        * `scripts` folder for the scripts (so basically everything which runs a loop through the whole session)
            * Seperation (if even needed) with a `server`, `client`, `shared` folder
        * `ui` folder for all dialogs or ui defines which are brought or needed by that module
        * `functions.hpp` to define the functions of this module
        * `globals.sqf` to define all global variables which are brought or needed by that module and aren't defined before
        * `initModule.sqf` which is called by all machines and where possible seperation for clients/HCs/Server will happen
        * `ui.hpp` to define the ui elements and dialogs from this module (will be included by the `KPLIB_ui.hpp` in the mission root)

**Comment by Tress16** [comment]
OK. Sounds nice.
