### ISSUE TITLE
Arsenal Restriction is not working. (Doesn't work for custom.sqf or other presets not changed by us)

### ISSUE THREAD

**Issue by Azi9Intent** [Wyqer/kp_liberation#300]
### Basic Information
**Mission version: 0.961**
**Map used: Sahrani **
**Mods used: CUP, RHS, TFAR, Ctab, ACE, ACEX, Some small weapon packs **
**Dedicated or local game? Attempted both, same issue. **
**GitHub or Workshop mission file? Workshop mission file, but it's been pulled from the workshop and edited seperately. **

### Individual Things
**Did you edit anything within the mission files?**

Yes

**If yes, what did you edit exactly?**

I personally wouldn't be able to say, a fair few things have gone into having things like ACE work the way we want it to, apart from that, only editing things like parameters and such, certain things in the kp_liberation_config.sqf 

### Short Issue Description

Arsenal is not restricting to our custom.sqf when mission is running

### Expected Behaviour

Arsenal to restrict to the class names we have in the custom.sqf

### Steps to Reproduce the Issue

With our mission file, simply running it.

### Screenshots, Serverlog or any other helpful Information

Entire (Unpacked) Mission file attached. (In a zip file)
[LibSahrani-v5A-0961.Sara.zip](https://github.com/Wyqer/kp_liberation/files/1557557/LibSahrani-v5A-0961.Sara.zip)

**Comment by Wyqer** [comment]
Referring to your missionfile.

kp_liberation_config.sqf

    /* Which arsenal preset should be used?
    0 = Use the default blacklist method (defined below).
    1 = Custom arsenal preset (edit the custom.sqf in the arsenal_presets\ folder to change things for your    own versions and tweaks).
    2 = Killah Potatoes Gaming Community arsenal preset.
    3 = RHS USAF arsenal preset.
    4 = RHS USAF arsenal preset with ACE.
    5 = RHS USAF arsenal preset with ACE and ACRE.	
    6 = 3cbBAF and RHS USAF arsenal preset. */
    KP_liberation_arsenal = 4;

You've set the Arsenal to RHS USAF with ACE and not to `1` for the custom.sqf. So it won't load your custom.sqf arsenal preset.

arsenal_presets\custom.sqf
line 482

    "APERSMine_Range_Mag"],[]],[["ACE_MX2A",

After changing the config to the value for the custom.sqf arsenal preset, it won't work, because you've this formatting mistake in your custom.sqf. Make sure to stick to the needed format. One comma after each element in the array and no comma after the last elemenent in an array.

    "APERSMine_Range_Mag",
    "ACE_MX2A",
