### ISSUE TITLE
AAF opfor preset integration to master trunk ? (file offer/suggestion)

### ISSUE THREAD

**Issue by zerxen** [Wyqer/kp_liberation#307]
### Foreword
Trying to find out if offering new variants via this (or BIS forum) or git commit is preferred for you guys

## Offer of AAF as opfor preset:
I and my buddies run a small coop server (arma.networkgeekstuff.com), but we hate to shoot CSAT "aliens" in vanilla, so we made a quick AAF as opfor preset that we think can be added to the master (since from vanilla perspective NATO vs AAF makes for better small team/small scale coop). Do you KP guys prefer manual adds via discussion in this ticket/forum or should we do git commit ? The change is miniscule with one new file and editing 2 core files:

### Changes to core files in human readble diff:
Changes to **presets/init_presets.sqf** and **kp_liberation_config.sqf** needed
[other_files_diff.txt](http://arma.networkgeekstuff.com/downloads/aaf_commit/other_files_diff.txt)

### AAF opfor preset to be added to /presets/opfor_presets dir:
[presets/opfor_presets/aaf.sqf](http://arma.networkgeekstuff.com/downloads/aaf_commit/aaf.sqf)

## Suggestion for future:
Can't the AAF items in blufor preset be made optional ? Or splitting the default custom.sqf blufor preset into two? One with AAF and one without? We are working on this as well on our side to avoid people buying AAF veh. and be teamkilled :)

**Comment by veteran29** [comment]
Usually contributors fork the repo and do a pull request. I prefer to create new features in separate branches then do a pull request.

IMO, AAF vehicles could be removed from default preset. NATO vehicles from same class/with same purpose are already in the preset.

Also u could add transport config for "I_Truck_02_covered_F" in addition to "I_Truck_02_transport_F".

**Comment by Wyqer** [comment]
> Do you KP guys prefer manual adds via discussion in this ticket/forum or should we do git commit ?

As @veteran29 already said a contribution is always very appreciated.
Best way would really be to fork, create a branch for the edits and afterwards open a pull request from the edits branch back to my master (or to the 0.97 branch, if you like to convert the old preset structure to the new one already)

> Can't the AAF items in blufor preset be made optional ? Or splitting the default custom.sqf blufor preset into two?

I don't think I would make it optional. The custom.sqf is a kind of "throw all possible things together" so that users can easily change it to their likings by remove unwanted stuff, change prices to "everything" and also provide a "automatic" mod adaption. Therefore a additional `non AAF` custom.sqf wouldn't be worth it in my opinion. It's easy enough to just remove the unwanted stuff in the "all together" custom.sqf.

**Comment by zerxen** [comment]
Well, two counter-points. 
1) Thanks for responses, I will create a branch and pull request to integrate the "AAF as enemy" presets to master. 
2) **@Wyger**, yes, but unfortunately the current implementation of max helos / max planes counts enemy planes into it if you simply use AAF as enemy. E.g. enemy base is activated and spawns planes/helos that are added to your blufor teams resource use, so my AAF opfor preset HAVE TO go together with "pure_nato.sqf" blufor preset.

**Comment by Wyqer** [comment]
> so my AAF opfor preset HAVE TO go together with "pure_nato.sqf" blufor preset

Yes, that's what I meant with "remove the unwanted stuff". Just remove all AAF vehicle classnames from your used preset and it's fine. You can also contribute a "pure vanilla blufor" preset, of course.
