### ISSUE TITLE
Respawn chopper lanuched into Air.

### ISSUE THREAD

**Issue by veteran29** [Wyqer/kp_liberation#310]
### Basic Information
**Mission version:** 0.963
**Map used:** Chernarus
**Mods used:** RHS

### Short Issue Description
Respawn chopper on carrier sometimes is launched into air.

### Expected Behaviour
Respawn chopper spawns and is not launched into air.

### Description
When I was creating AFRF preset I have moved helicopter spawns on carrier upward so helicopters spawned a bit above carrier deck and landed on it (commit: https://github.com/Wyqer/kp_liberation/commit/2e8521f08173fdb76787fc4a20cead35d027c59b). It was done to prevent some choppers from flying upon spawn.

I'm not entirely sure but I think this was reverted in commit: https://github.com/Wyqer/kp_liberation/commit/c4e37838d1472478ead14d6e0900196d95d18a84. When You were cleaning carrier deck from clutter.

### Possible fix
Move helicopter respawn markers above carrier deck.

### Steps to Reproduce the Issue
Launch mission, look at "huron", destroy it to force respawn. Easier to reporoduce with AFRF (8) preset.

### Screenshots, Serverlog or any other helpful Information
^^
![20180112222857_1](https://user-images.githubusercontent.com/4293906/34896423-1d6d7cb4-f7ea-11e7-8fa1-90a029e95141.jpg)

**Comment by Wyqer** [comment]
Strange, hrm.
The markers on the carrier are snapped to the surface of the deck and personally I haven't encountered that problem in our group (playing Lythium currently). I would say raising the marker wouldn't be the best solution. The snapping on the surface ensures, that it's equal on all maps. Makes it easier to track bugs instead of looking if on this map something is maybe .5m higher than in a map where something works, etc.
So for the next version I'll add a little offset for the spawning height.

Example for the current version:
https://github.com/Wyqer/kp_liberation/blob/a16b84e4612d8d0b9a167c41865f9c1c4ec2a44b/Missionframework/scripts/server/base/huron_manager.sqf#L19

    huron = huron_typename createVehicle [(getposATL huronspawn) select 0, (getposATL huronspawn) select 1, ((getposATL huronspawn) select 2) + 0.1];

This is than equal to the offset for the little birds spawn:
https://github.com/Wyqer/kp_liberation/blob/a16b84e4612d8d0b9a167c41865f9c1c4ec2a44b/Missionframework/scripts/server/base/startvehicle_spawn.sqf#L6

**Comment by veteran29** [comment]
I agree offset is better solution, it was a bit late and I proposed first solution that came to my mind :P

I think littlebird offset should a bit higher too, Ka60 rarely blows up too.  It is safer to spawn helis above deck than _in_ deck.

**Comment by veteran29** [comment]
I agree offset is better solution, it was a bit late and I proposed first solution that came to my mind :P

I think littlebird offset should a bit higher too, Ka60 rarely blows up too.  It is safer to spawn helis above deck than _in_ deck.

**Comment by GbAlien** [comment]
Maybe something with sea level. Waves keep changing the value. From [Bistudio Wiki](https://community.bistudio.com/wiki/Position#PositionATL) "Over sea it gets even more complicated as instead of PositionATL, PositionASLW is used minus the offset for the surface height, **presumably over waves** too, as z seems static."

**Comment by Wyqer** [comment]
The Freedom is a static object and not "swimming" or something. Therefore getting the ATL position and increase it from there is fine (sea ground on the ocean). Also because the position of the markers are "connected" to the surface of the carrier the getPos method would generally be not important in the end. As it don't creates the position via script, it takes the current position from an object and adds a offset.
