### ISSUE TITLE
Bug? Can't start secondary missions halfway into taking the map

### ISSUE THREAD

**Issue by ShamFleet** [Wyqer/kp_liberation#317]
We've just been trying to start ANY secondary missions and none will start. The cost of the mission is consumed and no mission will start. Is this intended?

**Comment by Wyqer** [comment]
Not basically "intended" but the way it works currently.
As soon as you captured a big part of the map the script can't find a suitable spot to spawn the mission. Condition is distance X to blufor sectors and distance Y to opfor sectors with X > Y. In a very progressed state there won't be a sidemission anymore. And the intel points are only used for that currently, so nothing like "omg, I lost intel points". They're useless at that state. Side effect is, that in the "endgame" the enemy is mostly at full aggressivity and it'll be much harder at the end.

**Comment by CreepPork** [comment]
@Wyqer but this shouldn't be considered as not a bug. It should display some kind of message to the user and return the intel points.

**Comment by Wyqer** [comment]
It's `no bug` because it's not intended to provide sidemissions in the end.
It's a "normal behaviour". Due to the refactoring there will be many changes to the way the scripts work and communicate with each other, which will most likely change also the sidemission behaviour.
And a return of the intel points is in the current state also nothing which would provide any "benefit", as they can only be spent for sidemissions currently. They're useless at that progress state at this moment.

Concerning a message, this would be something which is indeed helpful for the player, of course. But nothing I would provide now on the 0.963 state as another patch or update.

**Comment by CreepPork** [comment]
If side missions are not intended to be provided at the end game then why not remove the Action Menu entry altogether?

**Comment by Wyqer** [comment]
Can't say why it wasn't designed like that in the first place.
And I haven't changed it since 0.924 as I focused on other things.

**Comment by ShamFleet** [comment]
Hey thanks for the answer. Clears up a lot for me and the pals
