### ISSUE TITLE
Issue repeating action menu regardless of distance after Ai remote in

### ISSUE THREAD

**Issue by MikeX10** [Wyqer/kp_liberation#340]
### Basic Information
**Any Map**
**Map used:**
**Advanced Ai and recomended:**
**Personal Pc High end**
**Source of the mission file (URL) ??:**

### Individual Things
**Mission Parameters as Suggested**

**Mission parameters for personal pc**

### Screenshots, Serverlog or any other helpful Information;;;; 

Menu reads As this and then progressively,     Arsenal, Arsenal, Arsenal, Build, Build, build, Recycle,recycle,recycle.. ect and becomes accessible in any area on map.... # Note Not accessible when remoted in an Ai.

**Comment by amunoz20** [comment]
Hi, this issue has already been reported a while ago.

The reason this happens is because of Advanced AI Command mod, and has nothing to do with Liberation itself.

Having said that, @Wyqer has already said that he may (or may not) try to find a possible solution, but this issue has a low priority at this time.

A workaround for this issue is: Once you finish with the remote control of the AI, and if the problem shows up, commit suicide of your main character and menu should go back to normal when respawn back.

Some other problems may occur with Advanced Ai Command, eg:
When remote controling AI, your main character may be instructed to move to the last vehicle you mounted, or to a certain position in the map. So when you finish the remote control, your unit would be in a different place from where you left it.

**Comment by MikeX10** [comment]
Thank you for your quick response!
I thought it might be the case.. Thank you for your help.  I can turn off
Advanced Ai and perhaps just remote with Zeus...
At least now I can look at new angles..

It truly has been an excellent persistent campaign thank you.
