### ISSUE TITLE
Unable to capture AI Bases

### ISSUE THREAD

**Issue by Dubjunk** [Wyqer/kp_liberation#342]
### Basic Information
**Mission version:** 0.963
**Map used:** Altis
**Mods used:** http://steamcommunity.com/sharedfiles/filedetails/?id=1308553600 + VCOM AI
**Dedicated or local game:** Dedicated
**Source of the mission file (URL):** https://cdn.discordapp.com/attachments/401424294032310272/418534957317750794/kp_liberation.Altis.pbo

### Individual Things
**Did you edit anything within the mission files?**
Yes.

**If yes, what did you edit exactly?**
Modified different values and scripts.

### Short Issue Description
Sometimes enemy Bases can't be captured, there are no Enemys left but the Base is still Red.

### Expected Behaviour
The Base should get captured.

### Steps to Reproduce the Issue
unknown

### Screenshots, Serverlog or any other helpful Information
https://cdn.discordapp.com/attachments/410163915968741386/418527871049662464/IMAG0314.jpg

**Comment by PhantomViper** [comment]
Was experiencing similar issues on my friends server but his game was all wacked out and was having [other issues](https://github.com/Wyqer/kp_liberation/issues/341) too.

**Comment by Wyqer** [comment]
How long is the server running without a restart until this happens?

**Comment by Dubjunk** [comment]
Server was running ~4h with 20 +-2 Players. 2 sectors were active.

**Comment by phr0gz** [comment]
Same here! I reduced, civilian presence, and decreased the cleanup vehicle time to one hour and locked the server with verifysignatures to 2. I just tried to play alone like that yesterday for 6 hours and it was OK, will see if it stable with more than one player later.

It seems to happen (more often on big maps like Altis) when the server is "unresponsive" (and the savegame is not working), for example because a civilian car keep exploding somewhere in the map (I' don't know why).

When the server is "unresponsive", you can also have the ennemies that re-spawn around you, when you are trying to take an objective.

I hope that somehow it will help to solve the issue.
