### ISSUE TITLE
Arsenal forcibly Blacklisting items

### ISSUE THREAD

**Issue by PurgenChikatilo** [Wyqer/kp_liberation#344]
### Basic Information
**Mission version:** 
0.963
**Map used:** 
Chernarus
**Mods used:** https://cdn.discordapp.com/attachments/315696454373212161/418646067924566017/137.html
**Dedicated or local game:** 
Both, neither change the effect on error.
**Source of the mission file (URL):** https://cdn.discordapp.com/attachments/315696454373212161/418688270789115904/106_liberation.chernarus.pbo

### Individual Things
**Did you edit anything within the mission files?**

A bunch.

**If yes, what did you edit exactly?**

Presets for loadouts and sides, but the arsenal preset is giving me issues right now.

### Short Issue Description

Custom Arsenal set, all good. Everything works fine, close the Arsenal ingame and I get error messages stating that the following item is not allowed.
Tried couple of ways to fix, made sure the items are not on the blacklist, added the items forcibly to the whitelist of the kp configuration file, wiped the blacklist clean. Didn't work.

### Expected Behaviour

Some items, not all, will be the cause of the error, forcing your loadout to be wiped clean upon exiting the Arsenal and leaving you naked.

### Steps to Reproduce the Issue

No idea, all I did was set the items in the custom Arsenal.

### Screenshots, Serverlog or any other helpful Information

https://i.imgur.com/W9FrJsx.png

**Comment by Dubjunk** [comment]
Same Issue on my Server. Random items on Arsenal Whitelist are forbidden.

**Comment by PurgenChikatilo** [comment]
If possible, I would love to disable Arsenal. Will help get the issue out of the way and create zones for special equipment.

**Comment by Takahashi-Yuuki** [comment]
Looking at your modlist, you may be running afoul of animated sights. I'm running a game using CUP, and the RPG-7 has an animated sight that caused this issue. Basically what was going on, was that in order to animate the sight, multiple sight attachments were attached and removed by a script as the sight was adjusted. So you would have a 50m, 100m, etc being attached and removed. So pay attention to the error message, if it looks anything like MOD_RIFLE_50m  Then you haven't added the sights to the whitelist. I'm not sure about that vest, but it might be something similar.

**Comment by PurgenChikatilo** [comment]
It isn't just a vest, it's most of the uniforms, vests and helmets actually.
Sometimes even the rifles, even tho the attachments that go for the default rifle are also present in the arsenal to make sure I have no issues, but it's not exactly going as planned anymore.

I really am at a loss as to what could be causing this, because in that case I would assume that the RPG sights are fucky, altho I only have the ironsighted one available.
