### ISSUE TITLE
AI way too difficult.

### ISSUE THREAD

**Issue by DarkSideDK** [Wyqer/kp_liberation#370]
The AI is insane in this map. They will notice me after too bursts of fire, even with a suppressor and headshot me from 700 meters distance. There is literally no reason to do anything but day-time missions, because they AI spots me easier than I can see them during the night. And don't even get me started on vehicles and their accuracy.

How do I change this? Changing the difficulty for the server hasn't done anything.
Is there something else I need to change?

This is the config file listed below. 

```
class Difficulties
{
	class Recruit
	{
		class Flags
		{
			Armor=1;
			FriendlyTag=1;
			EnemyTag=1;
			HUD=1;
			HUDPerm=1;
			HUDWp=1;
			HUDWpPerm=1;
			WeaponCursor=1;
			AutoAim=1;
			AutoGuideAT=1;
			3rdPersonView=1;
			ClockIndicator=1;
			Map=1;
			Tracers=1;
			AutoSpot=1;
			UltraAI=0;
			DeathMessages=1;
			NetStats=1;
			VonID=1;
		};
		skillFriendly=0.34999999;
		skillEnemy=0.34999999;
		precisionFriendly=0.2;
		precisionEnemy=0.2;
	};
	class Regular
	{
		class Flags
		{
			Armor=1;
			FriendlyTag=1;
			EnemyTag=0;
			HUD=1;
			HUDPerm=0;
			HUDWp=1;
			HUDWpPerm=1;
			WeaponCursor=1;
			AutoAim=0;
			AutoGuideAT=0;
			3rdPersonView=1;
			ClockIndicator=1;
			Map=1;
			Tracers=1;
			AutoSpot=0;
			UltraAI=0;
			DeathMessages=1;
			NetStats=1;
			VonID=1;
		};
		skillFriendly=0.44999999;
		skillEnemy=0.44999999;
		precisionFriendly=0.5;
		precisionEnemy=0.5;
	};
	class Veteran
	{
		class Flags
		{
			Armor=0;
			FriendlyTag=0;
			EnemyTag=0;
			HUD=1;
			HUDPerm=0;
			HUDWp=1;
			HUDWpPerm=1;
			WeaponCursor=0;
			AutoAim=0;
			AutoGuideAT=0;
			3rdPersonView=0;
			ClockIndicator=1;
			Map=0;
			Tracers=1;
			AutoSpot=0;
			UltraAI=0;
			DeathMessages=0;
			NetStats=0;
			VonID=1;
		};
		skillFriendly=0.75;
		skillEnemy=0.75;
		precisionFriendly=0.1;
		precisionEnemy=0.1;
	};
	class Expert
	{
		class Flags
		{
			Armor=0;
			FriendlyTag=0;
			EnemyTag=0;
			HUD=1;
			HUDPerm=0;
			HUDWp=1;
			HUDWpPerm=1;
			WeaponCursor=0;
			AutoAim=0;
			AutoGuideAT=0;
			3rdPersonView=0;
			ClockIndicator=1;
			Map=0;
			Tracers=1;
			AutoSpot=0;
			UltraAI=0;
			DeathMessages=0;
			NetStats=0;
			VonID=0;
		};
		skillFriendly=0.94999999;
		skillEnemy=0.94999999;
		precisionFriendly=0.15000001;
		precisionEnemy=0.15000001;
	};
};
singleVoice=0;
maxSamplesPlayed=96;
sceneComplexity=400000;
shadowZDistance=100;
viewDistance=2000;
preferredObjectViewDistance=800;
terrainGrid=25;
volumeCD=10;
volumeFX=10;
volumeSpeech=10;
volumeVoN=10;
vonRecThreshold=0.029999999;

```

**Comment by veteran29** [comment]
Are you using current version of mission?

Older versions were overwriting ai settings but current versions are not touching AI skills.

**Comment by Wyqer** [comment]
> The AI is insane in this map

The AI skill isn't set by the map (terrain) of a mission. And the mission itself also don't affect any individual AI skills.

Concerning the question of @veteran29 the template you've deleted before you've entered your text is something which should be recognized, as it asks necessary informations concerning issue reports.

Well in this case it's not a bug or issue with the mission. Your difficulty settings concerning the AI and general difficulty on the server are deprecated by the way.
I recommend to have a look at these two links and adjust your serverside settings accordingly, as the experienced behaviour is caused by your server configuration.

https://community.bistudio.com/wiki/Arma_3_Difficulty_Menu#Configuration
https://community.bistudio.com/wiki/server.armaprofile#Arma_3
