### ISSUE TITLE
Ranking System

### ISSUE THREAD

**Issue by jus61** [Wyqer/kp_liberation#4]
Would like if there could be an optional ranking system!

If activated, the player should get experience points per kill, helping capturin sectors, Revive
, follow commander orders, etc. which will allow him to rise in rank and thus get better weapons and equipment.

**Comment by Wyqer** [comment]
Will have a look into that.
Maybe with a light script version of the [KP Ranks](http://steamcommunity.com/sharedfiles/filedetails/?id=741621641) mod for visualization.
Will have some thoughts about it.

**Comment by deveyus** [comment]
This seems blatantly open for abuse:
- Sit on server mostly afk to gain exp
- EXP per kill rewards players for roles people already want
- Aiding in capture encourages allowing sectors to be retaken, so you can capture more.
- Revives encourages shooting allies and not aiding them so that you can revive them more
- Following commander orders allows for two people to 'order trade' back and forth a bit.

A system like this however for NPCs could be quite good, making them better and worth saving, rather than disposable cannon fodder.

**Comment by Wyqer** [comment]
I personally also wouldn't not play in our community with this system, as we're organizing ourself etc.
And for sure it would be only an optional feature, if it will be done.

It's mostly a "I can provide some things, but what people do with it or how they abuse it is their thing"
And you're right with your points, sure. It can easily be abused by people who want to.

About NPCs:
I mostly don't planning to involve NPCs more than they already are, because Liberation should encourage people to play in larger groups to experience a immersive "part in a whole thing" feeling.
But sure, that's generally only my personal opinion.

**Comment by dragonspride1995** [comment]
Perhaps you could incorporate this experience system to chose different roles, and everyone starts out as a basic rifleman with restrictions on equipment?

**Comment by Wyqer** [comment]
Yeah, something like that.
I'll make some lists or overviews, when I start working on this system.
At the moment I'm working on the resource system.
