### ISSUE TITLE
0.95 FOB Buildings move on restart of the server

### ISSUE THREAD

**Issue by JamieKG** [Wyqer/kp_liberation#48]
I've noticed buildings have moved after a server restart 
this http://i.imgur.com/xjP6zdU.jpg
will turn into this http://i.imgur.com/9BtXYiS.jpg
that is from one server restart

**Comment by Wyqer** [comment]
This was always a problem in Liberation, yes.
I've already tried to find a way to prevent it from happen (disable collision while savegame load placing, use other position formats, etc.) but it won't work.
Analysing the savegames over some save / loads resulted in this sheme:
Save with positions "1"
Save is in profile with positions "1"
Loaded savegame places everything with positions "1"
Next save will save positions "2"
and so on.

So it has to be something while placement or with position reading during the game. Mostly it happens to walls, because they are very near to each other. But even with using "CAN COLLIDE" during placement, it don't fix it.
So at the moment I'm not able to fix it and won't be looking into that during 0.95 development (if no one has a great idea, fix or hint which I haven't tried already).
During the Code optimization phase after 0.95 release, I'll maybe have a way to prevent it or at least try it again.
