### ISSUE TITLE
Collect Ideas for Senseful Sidemissions

### ISSUE THREAD

**Issue by Wyqer** [Wyqer/kp_liberation#7]
Which sidemissions are senseful to add?
How should each sidemission impact the mission?

**Comment by svamp3717** [comment]
Hearts and minds type of missions maybe? Like blow up all remaining IEDs in a town, or deliver food packages from the main base to somewhere. Opfor militia could be spawned in the town to disrupt the IED clearing, and maybe even planes to bomb the supply trucks. Finding and blowing up ammo caches could also be an side mission, could serve as an spawn point for opfor militia until its cleared out.

**Comment by Wyqer** [comment]
Militia camps will be a important thing if I start working on a civil support system. So you could deliver resources to them, to increase their strenght or destroy them if the civilians work against you and your way of fighting.
But as mentioned in #10, that'll be something in the future, as the project should not be finished tomorrow and can't be.

**Comment by TahMahn** [comment]
Convoy Security/Attack:

This brings two mission types as I see it, where you either escort a convoy from point A to B, or you assault a convoy moving between B and C. Either way, could be cool to see.

Sabotage:

Basic sabotage, destroy/disable certain objects/vehicles. Like radio towers, or expensive aircrafts. Or factories, for that matter.

Capture:

Capture the HVT and bring him/her back to a FOB/the base. This one would probably be cool, but maybe a bit difficult to make happen. 

Checkpoint control:

Where you guard a checkpoint and check vehicles for IEDs or enemy contacts. Could be cool to introduce after a campaign has been going a while. 

Could also add non-combat missions, like transporting weapons/ammo from the Base to a FOB. Though that would mostly just be something for the pilots to do :P

I might get more ideas later, hope you don't mind if I spam you with them :)

**Comment by dragonspride1995** [comment]
My Wishlist

Much more variations in side objectives.
More ways to gather intel
Assassination missions
Better building mod, and more objects to build with.

**Comment by kaso2mod** [comment]
I'm working on two side mission but i don't know if you like my idea:
1- Search and Rescue the hostage
2- Search and Disarm the nuclear bomb
I summarized very much , the missions are much more articulate I just wanted to understand if the idea is it good  or not .
Thanks for suggestions

**Comment by Wyqer** [comment]
A kind of hostage rescure was also on my mind, yes.
I still think about a nice way to implement something like "civil meaning". So it would offer a dimension for supply transports, disarm minefields, etc.

**Comment by amunoz20** [comment]
I've been thinking about this for a while now. It would be cool to have something like this:

1. Assassination: Any enemy force has to have a chain of command, this type of missions will allow you to strike at important members of that chain of command, which will help you reduce your notoriety. It could also be added as one of the main objetive of Liberation "to kill certain high ranking officer". In order to make this mission not so repetitive, the objetctive could traveling by air, land or sea from A to B or just be sitting around on certain point.

2. Steal Intel: raid a camp, take suit case, kill anyone in your way. This will give you intel points

3. Hack the terminal: this mission is similar to steal the intel but after you active the uplink you have to defend the area for a certain amount of time.

4. Destroy the vehicle: Sabotage mission that will reduce your notoriety. The vehcle could be one (or more) truck, tank, helicopter, jet... etc

5. Destroy the artillery: Same idea as point 4, the difference is that this could have a higher impact. Example: "You have 5 minutes to destroy that MLRS otherwise it will bomb X FOB or Factory". This will reduce notoriety and save yo ass. (it could also be possible to capture [?] the MLRS instead of destroying it)

6. Raid the supply line: Attack the convoy, steal the resources.

7. Rescue the hostage: Self explanatory, however it could be not only military personel. This could involve the rescue of important civillian people in exchange for intel.

8. Capture the HVT: Self explanatory. It could be in exchange of intel (a lot!)

9. Aid the civis: War is also about helping civillians... This could be either sending them resources, heal the wounded, you name it... this will give you intel (later this could be transofrmed into some sort of loyalty and civis will help you fight the bad guys)

10. Checkpoint control: Rumor has it, there are smugglers entering some city delivering bombs, weapons, etc to the civis so they can revolt agains you, Its important to block the main streat of such city and find that lil bastard. This could give you intel, and some resources. ( the ones he had :P )

11. Secure the crash site: Self explanatory, in exchange for some resources and some intel.

12. Protect the convoy: Self explanatory, protect your resources or the VIP from A to B (where destination could be an airport, harbour... you name it)

13. Ambush: Set a surprise atack to get resources.

14. Clear the minefield: it could be one bomb sitting in the middle of the town, or it could be a complete mine field interrupting your supply line. You gotta clear that out.... oh you could get attacked while you do that tho... dont let your guard down!

15. Patrol the area: A small patrolling mission with the possibility of a small firefight, it could give you some intel, maybe nothing but It will still be fun af...

Thats it for now!
Cheers!

**Comment by Wyqer** [comment]
Oh, many thanks for the suggestions. :)
A "Raid the supply line" mission is already available btw. ;)

But I will definetly implement some of your suggestions when I'm adding more sidemissions.

**Comment by amunoz20** [comment]
Thanks man! And pls pls do implement #5 it will totally rock to have a mission like "do or die" :) 
If I come to have additional ideas I let ya know

**Comment by RaulPro19** [comment]
That's not a side mission but it could be nice to add random opfor checkpoints on roads that force you to destroy it or take another path.

**Comment by SondreBakken** [comment]
Adding a lot of variarity in sidemissions can be done two ways.. and in my opinion, one is right and the other one is wrong. Adding a lot of missionstypes that are always the same is wrong. If everytime you are to sabotage a radiotower there will be three soldiers patrolling in a 50 m radius this mission will be very boring quickly. So if every mission is this static it does not matter how many types. 

In my opinion you could do with 4-5 mission types but adding random mission parameters that require you to do some recon first. Is there any vehicles, what types of defences etc. And to add another layer to them you could have random events happening. Like a convoy of pickups arriving, a tank leaving.. maybe a helicopter landing, etc etc.

I remember playing a scenario where you would get sabotage missions where the defences would range from 3-5 tanks and 50 people, to none.  In some cases you did the recon and decided you could not do it. If you did the mission you would get some kind of a related bonus (support possibilies, supplies, etc), but if the defences were so heavy it wasnt worth the risk you could report back that its a no-go and lose the bonus and face a bit of penalty. 

Despite what you would believe the missions where there were no defences were quite enjoyable too. You did the recon, not knowing what to expect, and you would sneak down to whatever you were to blow up, expecting a helicopter, convoy or ambush at anytime. Once you got the charges in place you got out of there as fast as you could. The uncertainty and suspense were chilling.

**Comment by Wyqer** [comment]
I agree with the "randomized parameters" which should apply to each mission type.
After start of working on 96 (in about one week) I'll provide some more precise thoughts concerning missions (especially concerning civil reputation stuff), so we can all discuss aspects of them or even come to new ideas or conclusions.

**Comment by amunoz20** [comment]
I was thinking... One of the things I liked about Antistasi was the hability to go "undercover", following the idea of @SondreBakken and my own suggestion for man missions and side missions. I think it would be nice to be able to go undercover for some recon missions, maybe to extract some Intel, or to check the área and see if its possible to assault.. The undercover mode could open a New way to execute missions

**Comment by Wyqer** [comment]
There will be no undercover functionality or similar in Liberation. It's aimed for regular forces and not for guerilla groups. That's something what Antistasi is for and doing it really really good. ^^
And you're always able to do undetected recon missions or similar.... just don't get detected by the enemy.

So in general Liberation will always aim for a "regular forces" feeling and not for a "speacial forces", "guerilla group" or similar gameplay.

**Comment by amunoz20** [comment]
@wyqer well sad... But if its your final decision, it is what it is.. Just wanna say that not only guerrillas do undercover missions, still thanks

**Comment by Wyqer** [comment]
Closed.
Guess we've many good ideas here and we'll see what can be implemented during the next releases.
