### ISSUE TITLE
Dedicated Server Progress Reset Hangs on Mission Read (dev 0.95)

### ISSUE THREAD

**Issue by DrewGamer** [Wyqer/kp_liberation#77]
Trying to reset the progress of a dedicated server (using mission params) causes client to hang at the mission loading screen.

Steps to reproduce:
1) Have an already working instance of the mission (dev 0.95) on a dedicated server.
2) Launch dedicated server, launch client.
3) Connect to server, select mission and activate both progress wipe options
4) Launch mission

Other details:
- EDIT: This is on the Altis map
- No mods are being used for the server
- Mission seems to get past 1 loading screen, then flickers to the mission map screen (the one with the continue button) and then flickers back to the loading screen.
- Client stays like this for what appears indefinitely (alt-f4 required to exit client)
- Server seems fine and even registers that all clients have disconnected
- After this issue, the mission will no longer load at all (even without reset params)
- Locally hosted server works fine (no issues playing or resetting)

[arma3server_x64_2017-05-19_17-59-37.rpt.txt](https://github.com/Wyqer/kp_liberation/files/1015665/arma3server_x64_2017-05-19_17-59-37.rpt.txt)

**Comment by ChiefOwens** [comment]
I have the same issue as well. The last line of my .rpt matches the .rpt file above.

18:34:36 Class CBA_NamespaceDummy destroyed with lock count 1
18:34:36 Class CBA_Extended_EventHandlers_base destroyed with lock count 3
18:34:37 Extensions:

Using the following mods:
-serverMod=@AdvancedTowing;@AdvancedRappelling;@AdvancedSlingLoading;@AdvancedUrbanRappelling
-mod=@CBA_A3;@RHSUSAF;@RHSAFRF;@ATLAS;@AdvancedAICommand;@3cb_baf_equipment;@3cb_baf_units;@3cb_baf_vehicles;@3cb_baf_weapons

**Comment by k4s0** [comment]
Me too, i use this mod:
@cba
@task_force_radio

**Comment by Wyqer** [comment]
I'll have a look into that.
The rpt don't show any weird things in general and I personally didn't experienced it.
Which server do you use? Linux or Windows? Dedicated root or hosted server?
The thing is, that there wasn't any change to the save manager. There has to be some other issue maybe due to the update.
Did you all played with a fresh GitHub 0.95?

**Comment by ChiefOwens** [comment]
Downloaded the pbo you linked.
Windows Dedicated root server
Deleted .var. file and still same issues

Resetting using mission parameters seems to delete the old save, but it hangs and will not start. Restarting the arma server on the dedicated box and not using the parameters to reset right after brings up a fresh map (restart).

**Comment by Wyqer** [comment]
Hrm...
which map are you playing on?

I think it could be maybe something with user rights or anything..... preventing the missionscript to access the vars file or something maybe. I'll test it on our root server in the morning.
If you find some other clues or anything, please let me know.

**Comment by DrewGamer** [comment]
For me:
Generic Windows 10 copy with server created (strictly) following the dedicated server setup guide on BI forums (not sure what you mean by dedicated root or hosted).

Playing on vanilla Altis (no other mods / modifications).

**Comment by Wyqer** [comment]
Dedicated root like a "real server" with remote desktop or something.
Hosted server like the ones from the gameserver providers with only webinterface and FTP.

It would maybe be good if you all use the mission.pbo which is linked in the BI Forum:
https://forums.bistudio.com/forums/topic/202711-mpcti-coop-liberation-continued/?do=findComment&comment=3189935

Then try to reproduce it with that file without any edits or any mods.
If you can't reproduce it then, add your mods.
Again no reproduce, add your possible edits in the missionfile.

So we can maybe figure out if it's something with the logistics, the mods or the edits (the last one I wouldn't think is the issue).

If you can't reproduce it with that missionfile in the three steps, then it could be something with the carrier or even the ArmA Update itself. (But it can't really be the carrier edits, because Chief said he used the BI Forum Version).

**Comment by Wyqer** [comment]
Ok, just some new informations so far:

With the "Production finish" Experimental everyting is fine. With the "Logistic finish" experimental I can reproduce the same behaviour. (Beside of the MP issue, the SP from the editor won't start also)
But it all work fine if you start the mission as MP from the editor (that's why I maybe didn't noticed that)

For our session this evening I had also the same issue and found a workaround -> starting the server with autoInit will work.
And it seems the issue will only happen to the first player(s) which are joining, not the following. Also that during autoInit the initialization will work shows that it should be something there. And I've noticed that you don't see the map screen at the moment in dedicated MP (in local Editor MP there is the map screen before start).

So it has to be something between "finishing production" (ac3a83f2385b9b7abb1a9125817b98f6aaec4369) and "finishing logistics" (0758e105877c93a6682f5dc41194c50fbb21adff).
