### ISSUE TITLE
suggestion: Add physical truck to AI logistics

### ISSUE THREAD

**Issue by CurePindal** [Wyqer/kp_liberation#98]
Yesterday I started a new game and looted a truck from the enemy. Had not much resources so it would have been wonderful if we could add physical trucks to the AI logistics system, instead of buying them.
Worth a consideration?
Edit: Civ trucks that cruise the island are easy to exploit. So I would restrict this to the captured, military trucks only.

**Comment by Wyqer** [comment]
Personally I would think no, but I always appreciate more opinions.

Reasons:
Players could start to just capture maybe civilian vans or trucks to use them for the logistic.
Maybe the trucks are only able to carry 2 crates instead of 3 as the logi trucks.
Next suggestion would maybe be, to "spawn trucks with remove one from a logi group".
Logi groups could then be used as "indestructible storage for trucks".
Way to exploit (example): Truck would give 40S and 40F for recycle, put them in the logi group, get 50S and 50F for it.

**Comment by amunoz20** [comment]
Im not sure if I understood this correctly but maaaaaaaybe it could only be possible to allow physical trucks as long as they are military trucks?? I mean it could still be exploited but well if you wanna cheat theres like 300 ways to cheat. Example: use the console of the game to spawn expensive vehicles you already can buy and recycle them for free ammo (I have never done it :P)

I think that the person(s) who wants to play fair will play fair... what I wouldnt recomend is to let the AI physically drive the damn truck, nor allow to have multiple trucks driven by AI at the same time all over the AO because that would literally kill game performance...

Or maybe I just get all this wrong from the OP

**Comment by Wyqer** [comment]
Sure, everyone can "cheat" with the console if they want and know how to do it. I even say people how, if they ask (mostly to lower enemy awareness etc.)
But I think it's one thing to just use the normal ArmA ways then "providing" something which can be easily used as exploit.
Sure, in "closed communities" it won't be a problem, but same for the asked "better check if someone has a blacklisted item" (#14) this could be a problem for people who want to run a public server and then has to check if someone is exploiting or cheating.
As I said, let's look / wait for some other opinions. :)

**Comment by CurePindal** [comment]
Not thought about the civ trucks that cruise around the island, so I would indeed adjust my suggestion to military trucks only without. 

Quote: "Next suggestion would maybe be, to "spawn trucks with remove one from a logi group".
No offense, but thats not an argument, denying suggestions because they MIGHT lead to other, non-related suggestions. (Dont grant your kid an ice because it might request an Audi next time....??? Ilogical.)

**Comment by Wyqer** [comment]
And I didn't denied it with this as argument. Still pending and open for discussion about it.
The listed reasons are things everyone should have in mind, if thinking about this suggestion.
It was also not the only thing I mentioned.

**Comment by CurePindal** [comment]
Sorry, for the misunderstanding but I havent said you did. That comment was subjunctively.
